version: '3.8'

services:
  server-guard:
    container_name: server-guard
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "7777:7777"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777/metrics"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 2m
    depends_on:
      - prometheus
      - grafana
      - surrealdb
      - valkey
    environment:
      - DATABASE_IP=surrealdb
      - GRAFANA_ROOT=http://grafana:3002
      - PROMETHEUS_ROOT=http://prometheus:9090
      - VALKEY_IP=valkey
    restart: always

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - "8000:8000"
    command:
      - start
      - --log=trace
      - --auth
      - --user=root
      - --pass=root
      - file://database.db
    volumes:
      - ./data/surrealdb.db:/database.db
    restart: always
  
  valkey:
    image: valkey/valkey:7.2
    container_name: valkey
    command:
      - valkey-server
      - /valkey.conf
    volumes:
      - ./config/valkey.conf:/valkey.conf
    expose:
      - "6379"
    restart: always
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "0"
    environment:
      GF_LOG_LEVEL: error
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    volumes:
      - ./config/grafana:/etc/grafana
      - ./config/dashboards:/tmp/dashboards
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3002:3002"
    restart: always
  
  loki:
    container_name: loki
    image: grafana/loki:latest
    user: root
    expose:
      - "3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki.yml:/etc/loki/local-config.yaml
    restart: always

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    user: root
    volumes:
      - /var/log:/var/log
      - ./config/promtail.yml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    restart: always
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.2.1
    user: root
    command:
      - --log.level=error
      - --storage.tsdb.path=/data/prometheus
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data:/data
    restart: always

networks:
  default:
    name: serverguard